"use client";
import React, { useEffect } from "react";
import { Label } from "./ui/label";
import { Font } from "@/generator-types/FontPairing";
import FontSelector from "./FontSelector";
import localFont from "next/font/local";
import { generateSkibidiIpsum } from "@/utils/skibidiIpsum";
import Link from "next/link";

const fetchFont = async (familyName: string) => {
  const formattedName = familyName.replace(" ", "+");
  const resp = await fetch(`http://localhost:8080/?fontName=${formattedName}`, {
    method: "GET",
  })
    .then((res) => res.blob())
    .then((blob) => blob.arrayBuffer())
    .then((buffer) => Buffer.from(buffer).toString("base64"));
  return resp;
};

const skibidiIpsum = generateSkibidiIpsum(4);

const FontPairingBody = ({ fonts }: { fonts: Font["items"] }) => {
  const [headingFont, setHeadingFont] = React.useState("");
  const [paragraphFont, setParagraphFont] = React.useState("");
  const [headingFontByteCode, setHeadingFontByteCode] = React.useState("");
  const [paragraphFontByteCode, setParagraphFontByteCode] = React.useState("");

  useEffect(() => {
    if (headingFont) {
      (async () => {
        const f = await fetchFont(headingFont);
        setHeadingFontByteCode(f);
      })();
    }
  }, [headingFont]);

  useEffect(() => {
    if (paragraphFont) {
      (async () => {
        const f = await fetchFont(paragraphFont);
        setParagraphFontByteCode(f);
      })();
    }
  }, [paragraphFont]);

  return (
    <div className="grid-cols-[700px_1fr] grid gap-20">
      <style jsx global>{`
        @font-face {
          font-family: "HeadingFont";
          src: url("data:application/x-ttf;base64,${headingFontByteCode}");
          font-variant-synthesis: individual, legacy;
        }

        @font-face {
          font-family: "ParagraphFont";
          src: url("data:application/x-ttf;base64,${paragraphFontByteCode}");
          font-variant-synthesis: individual, legacy;
        }
        .preview-heading {
          font-family: "HeadingFont", "geistSans";
        }
        .preview-paragraph {
          font-family: "ParagraphFont", "geistSans";
        }
      `}</style>
      <section className="border border-border p-4 rounded-xl bg-muted/30">
        <header className="mb-6">
          <h2 className="h2 ">Fonts</h2>
          <p className="text-muted-foreground">
            This font pairing utiliteehee uses Google fonts to deliver you the
            best fonts in the universe.
          </p>
        </header>
        <div className="flex gap-4">
          <div className="flex flex-col gap-2 w-full">
            <Label>Heading font</Label>
            <FontSelector
              fonts={fonts}
              value={headingFont}
              setValue={setHeadingFont}
            />
          </div>

          <div className="flex flex-col gap-2 w-full">
            <Label>Paragraph font</Label>
            <FontSelector
              fonts={fonts}
              value={paragraphFont}
              setValue={setParagraphFont}
            />
          </div>
        </div>
      </section>

      <section className="rounded-xl overflow-hidden border border-border">
        <header className="w-full flex bg-foreground/10 p-4  gap-2">
          <span className="bg-foreground/20 h-3 w-3 rounded-full block"></span>
          <span className="bg-foreground/20 h-3 w-3 rounded-full block"></span>
          <span className="bg-foreground/20 h-3 w-3 rounded-full block"></span>
        </header>
        <div className="p-10  max-w-2xl mx-auto">
          <p className="text-3xl font-bold preview-heading mb-6">
            The quick brown fox jumped over the lazy dog.
          </p>

          <div className="flex flex-col gap-4">
            {skibidiIpsum.map((p, i) => (
              <p className="preview-paragraph text-foreground/70" key={i}>
                {p}
              </p>
            ))}
          </div>
          <Link
            href="/generators/skibidi-ipsum"
            className="underline text-muted-foreground text-xxs mt-10 block"
          >
            Placeholder text generated by Skibidi Ipsum
          </Link>
        </div>
      </section>
    </div>
  );
};

export default FontPairingBody;
