import Link from "next/link";
import React from "react";

const FontPairingPreview = ({ text }: { text: string[] }) => {
  return (
    <section className="rounded-xl overflow-hidden border border-border bg-muted/30">
      <header className="w-full flex bg-foreground/10 p-4  gap-2">
        <span className="bg-foreground/20 h-3 w-3 rounded-full block"></span>
        <span className="bg-foreground/20 h-3 w-3 rounded-full block"></span>
        <span className="bg-foreground/20 h-3 w-3 rounded-full block"></span>
      </header>
      <div className="p-10  max-w-2xl mx-auto ">
        <p
          className="text-3xl font-bold preview-heading mb-6"
          contentEditable={true}
          suppressContentEditableWarning={true}
        >
          The quick brown fox jumped over the lazy dog.
        </p>

        <div className="flex flex-col gap-4">
          {text.map((p, i) => (
            <p
              className="preview-paragraph text-foreground/70"
              key={i}
              contentEditable={true}
              suppressContentEditableWarning={true}
            >
              {p}
            </p>
          ))}
        </div>
        <Link
          href="/generators/skibidi-ipsum"
          className="underline text-muted-foreground text-xxs mt-10 block"
        >
          Placeholder text generated by Skibidi Ipsum
        </Link>
      </div>
    </section>
  );
};

export default FontPairingPreview;
